"use client";

import { Check, Loader2, LockKeyhole, ShieldCheck } from "lucide-react";
import { useState } from "react";
import type { Offer } from "@/lib/offers";
import { trackEvent } from "@/lib/analytics-client";

export function CheckoutForm({ primary, bumps }: { primary: Offer; bumps: Offer[] }) {
  const [email,setEmail]=useState(""); const [selected,setSelected]=useState<string[]>([]); const [loading,setLoading]=useState(false); const [error,setError]=useState(""); const [complete,setComplete]=useState(false);
  const chosen=[primary,...bumps.filter(item=>selected.includes(item.slug))];
  const total=chosen.reduce((sum,item)=>sum+item.priceCents,0);
  async function submit(event:React.FormEvent){event.preventDefault();setLoading(true);setError("");trackEvent("InitiateCheckout",{product:primary.slug,value:total/100,currency:"USD"});try{const response=await fetch("/api/checkout/start",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email,items:chosen.map(item=>item.slug)})});const result=await response.json();if(!response.ok)throw new Error(result.error??"No fue posible iniciar el pago");if(result.mode==="external"){window.location.assign(result.next);return;}setComplete(true);}catch(cause){setError(cause instanceof Error?cause.message:"Ocurrió un error");}finally{setLoading(false);}}
  if(complete)return <div className="surface p-8 text-center"><span className="mx-auto grid size-14 place-items-center rounded-2xl bg-[#e4e9df] text-[#547055]"><Check/></span><h2 className="editorial-title mt-5 text-4xl">Compra simulada confirmada.</h2><p className="mt-4 leading-7 text-muted">Crea tu cuenta con <strong>{email}</strong> para que el acceso se vincule automáticamente.</p><a href="/registro" className="primary-button mt-6">Crear mi acceso</a><p className="mt-4 text-xs text-muted">Este modo existe solo en desarrollo. Producción usa el checkout externo configurado.</p></div>;
  return <form onSubmit={submit} className="space-y-5"><div><label className="label" htmlFor="checkout-email">Tu email de acceso</label><input id="checkout-email" className="field" type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="maria@ejemplo.com" required/></div>{bumps.length?<div className="space-y-3"><p className="label">Completa tu experiencia (opcional)</p>{bumps.map(item=><label key={item.slug} className={`block cursor-pointer rounded-2xl border p-4 transition ${selected.includes(item.slug)?"border-[#B85C42] bg-[#fff7f2]":"border-[#ddd3c6] bg-[#fffdf8] hover:bg-[#f8f4ec]"}`}><span className="flex gap-3"><input type="checkbox" className="mt-1 size-4 accent-[#B85C42]" checked={selected.includes(item.slug)} onChange={()=>setSelected(current=>current.includes(item.slug)?current.filter(slug=>slug!==item.slug):[...current,item.slug])}/><span className="flex-1"><span className="flex justify-between gap-3 font-semibold"><span>{item.shortTitle}</span><span>+US${(item.priceCents/100).toFixed(2)}</span></span><span className="mt-1 block text-sm leading-6 text-muted">{item.description}</span></span></span></label>)}</div>:null}<div className="rounded-2xl bg-[#282621] p-5 text-white"><div className="flex justify-between gap-4 text-sm text-white/65"><span>{chosen.length} producto{chosen.length>1?"s":""}</span><span>Pago único</span></div><div className="mt-2 flex items-end justify-between"><span className="text-sm">Total</span><strong className="text-3xl">US${(total/100).toFixed(2)}</strong></div></div>{error?<p className="error-text">{error}</p>:null}<button className="primary-button w-full" disabled={loading}>{loading?<Loader2 size={18} className="animate-spin"/>:<LockKeyhole size={18}/>} {loading?"Preparando…":"Continuar al pago seguro"}</button><div className="flex items-start gap-2 text-xs leading-5 text-muted"><ShieldCheck size={16} className="mt-0.5 shrink-0 text-[#74836B]"/><span>15 días de garantía. Acceso personal a la versión adquirida. La plataforma de pago procesa tus datos financieros.</span></div></form>;
}
